version: '3.8'

services:
  # Application service
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_ANON_KEY=${SUPABASE_ANON_KEY}
      - SUPABASE_SERVICE_ROLE_KEY=${SUPABASE_SERVICE_ROLE_KEY}
      - LOG_LEVEL=info
      - CORS_ORIGIN=http://localhost:3000
    volumes:
      - ./logs:/app/logs
    restart: unless-stopped
    networks:
      - employee-management-network

networks:
  employee-management-network:
    driver: bridge