# Docker Compose override for development environment
# This file is automatically loaded by docker-compose and overrides settings in docker-compose.yml

version: '3.8'

services:
  app:
    environment:
      - NODE_ENV=development
      - LOG_LEVEL=debug
      - DEBUG=true
      - ENABLE_SWAGGER=true
    volumes:
      - .:/app
      - /app/node_modules
    command: ["npm", "run", "dev"]
    ports:
      - "3000:3000"
      - "9229:9229"  # Debug port

  postgres:
    environment:
      - POSTGRES_DB=employee_management_dev
    ports:
      - "5432:5432"

  redis:
    ports:
      - "6379:6379"